# Generated by Django 4.2.2 on 2023-06-23 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_color_size_remove_product_imgurl_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selectedColor',
            field=models.ManyToManyField(blank=True, null=True, related_name='selectedColor', to=settings.AUTH_USER_MODEL),
        ),
    ]
