# Generated by Django 4.2.2 on 2023-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_featuredin_remove_product_like_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=64),
        ),
    ]
