# Generated by Django 4.2.2 on 2023-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_featuredin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredin',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='app.product'),
        ),
    ]
