# Generated by Django 4.2.2 on 2023-06-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_featuredin_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inWishlist',
            field=models.BooleanField(default=False),
        ),
    ]
