# Generated by Django 4.2.2 on 2023-07-02 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_address_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inWishlist',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 5, 24, 37, 207454)),
        ),
    ]
